### ISSUE TITLE
(At least) GTDB fails to download

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo#171] opened 2023-08-25 15:01 UTC
### Description of the bug

I ran the test case with eukulele/gtdb but the download failed:

```
ERROR ~ Error executing process > 'NFCORE_METATDENOVO:METATDENOVO:SUB_EUKULELE:EUKULELE_DOWNLOAD ($meta.id)'

Caused by:
  Process `NFCORE_METATDENOVO:METATDENOVO:SUB_EUKULELE:EUKULELE_DOWNLOAD ($meta.id)` terminated with an error exit status (1)

Command executed:

  pushd eukulele
  
  EUKulele \
      download \
       \
      --database gtdb
  
  popd
  touch gtdb
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_METATDENOVO:METATDENOVO:SUB_EUKULELE:EUKULELE_DOWNLOAD":
      eukulele: $(echo $(EUKulele --version 2>&1) | sed 's/Running EUKulele with command line arguments, as no valid configuration file was provided.//; s/The current EUKulele version is//g')
  END_VERSIONS

Command exit status:
  1

Command output:
  ~/dev/nf-core-metatdenovo/work/17/8445ecb2cd7a6068a6d58fe253433f/eukulele ~/dev/nf-core-metatdenovo/work/17/8445ecb2cd7a6068a6d58fe253433f
  Running EUKulele with command line arguments, as no valid configuration file was provided.
  Specified reference directory, reference FASTA, and protein map/taxonomy table not found. Using database in location: ./gtdb.
  Automatically downloading database gtdb . If you intended to use an existing database folder, be sure a reference FASTA, protein map, and taxonomy table are provided. Check the documentation for details.
  Specified reference database, gtdb is not supported.

Command error:
  Unable to find image 'quay.io/biocontainers/eukulele:2.0.3--pyh723bec7_0' locally
  2.0.3--pyh723bec7_0: Pulling from biocontainers/eukulele
  73349e34840e: Already exists
  acab339ca1e8: Already exists
  935c26139724: Pulling fs layer
  935c26139724: Verifying Checksum
  935c26139724: Download complete
  935c26139724: Pull complete
  Digest: sha256:7933d7d1a2a15a96aef32fd3c49edecb5a5850de0c344ff3920a06a135267578
  Status: Downloaded newer image for quay.io/biocontainers/eukulele:2.0.3--pyh723bec7_0
  ~/dev/nf-core-metatdenovo/work/17/8445ecb2cd7a6068a6d58fe253433f/eukulele ~/dev/nf-core-metatdenovo/work/17/8445ecb2cd7a6068a6d58fe253433f
  Running EUKulele with command line arguments, as no valid configuration file was provided.
  Specified reference directory, reference FASTA, and protein map/taxonomy table not found. Using database in location: ./gtdb.
  Automatically downloading database gtdb . If you intended to use an existing database folder, be sure a reference FASTA, protein map, and taxonomy table are provided. Check the documentation for details.
  Specified reference database, gtdb is not supported.

Work dir:
  /home/daluab/dev/nf-core-metatdenovo/work/17/8445ecb2cd7a6068a6d58fe253433f

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

A `gtdb` subdirectory was created in `eukulele` but it was empty.

Invoking `EUKulele download --database gtdb` from the terminal seems to work fine.

### Command used and terminal output

```console
# Without having a downloaded gtdb database:
nextflow run . -profile test,docker -resume --assembler rnaspades --eukulele_db gtdb --skip_eukulele false
```

**Comment by danilodileo** [comment] 2023-08-28 01:54
Could it be EUKulele old version? I can take a look

**Comment by danilodileo** [comment] 2023-08-28 03:19
By changing the container, the error persists. The module is able to download the `reference.pep.fa` and `taxonomy-table.txt` but fails to download the protein table `prot-map,json` . I would try to download all the files outside the module with the same version to be sure nothing is wrong in the EUKulele version

**Comment by erikrikarddaniel** [comment] 2023-08-28 06:08
I did just that and it worked fine: Download with Eukulele outside the workflow, then run the workflow with downloaded files.

**Comment by danilodileo** [comment] 2023-08-28 07:25
I am trying to download another database (PhyloDB) through metatdenovo. if it not working then the issue is in our code

**Comment by danilodileo** [comment] 2024-07-24 13:17
This issue can be closed as we don't have any module EUKULELE:DOWNLOAD. but the issue on downloading GTDB persist and it's reported in another issue #256

**Closed as completed by danilodileo** 2024-07-24 13:17 UTC
Labels: bug

**Comment by akrinos** [comment] 2024-07-31 20:06
Just putting a comment here that I will be addressing this issue within EUKulele in a release in the next 2 weeks. In the meantime, there is a workaround for using the standalone EUKulele tool and attempting this download https://github.com/AlexanderLabWHOI/EUKulele/issues/58
